### ISSUE TITLE
Error en controlador PID desconocido cuando corro xarm6_challenge.launch como venia del git

### ISSUE THREAD

**Issue by joseangeldelangel10** [Manchester-Robotics/ManipulatorsFeb2022-Students#10]
Hola, solo queria informar que cuando hago el roslaunch de xarm6_challenge.launch la terminal me muestra un error en los controladores pid de las uniones del robot  (aunque gazebo cargue el modelo del robot, la mesa y los bloques sinproblemas) , el error es que no se especifico una ganancia proporcional en los controladores, intente buscar el .yaml file donde vinieran las definiciones de los controladores pero al parecer hay varios en diferentes locaciones y el namespace que se muestra en el error no da un indicio de en que carpeta se encuentra ni a que controlador se refiere (velocidad, ezfuerzo, etc.). Primero que nada quería saber si este error es normal y si puedo seguir trabajando la solucion aun con este error o si debo corregir un .yaml file o algo similar quisiera saber si me podrian indicar cual. Adjunto un code snippet de lo que me aparece en la terminal. :)   

```
[INFO] [1646635926.871331, 0.000000]: Calling service /gazebo/set_model_configuration
[INFO] [1646635926.876637, 0.000000]: Set model configuration status: SetModelConfiguration: success
[INFO] [1646635926.879059, 0.000000]: Unpausing physics
[ERROR] [1646635926.935950124]: No p gain specified for pid.  Namespace: /xarm/gazebo_ros_control/pid_gains/joint1
[ERROR] [1646635926.937666183]: No p gain specified for pid.  Namespace: /xarm/gazebo_ros_control/pid_gains/joint2
[ERROR] [1646635926.939775638]: No p gain specified for pid.  Namespace: /xarm/gazebo_ros_control/pid_gains/joint3
[ERROR] [1646635926.941674811]: No p gain specified for pid.  Namespace: /xarm/gazebo_ros_control/pid_gains/joint4
[ERROR] [1646635926.943478119]: No p gain specified for pid.  Namespace: /xarm/gazebo_ros_control/pid_gains/joint5
[ERROR] [1646635926.945899745]: No p gain specified for pid.  Namespace: /xarm/gazebo_ros_control/pid_gains/joint6
[ INFO] [1646635927.026942742]: Loaded gazebo_ros_control.

```

**Comment by MarcFacerias** [comment]
Si somos conscientes, ese error no afecta al actual modo de trabajo. Si no recuerdo mal se utiliza en el caso de quere controlar la fuerza que ejerce el robot (actualmente solo controlamos la posición)

Un saludo,
Marc
