### ISSUE TITLE
Error con catkin_make

### ISSUE THREAD

**Issue by GerardoA01701474** [Manchester-Robotics/ManipulatorsFeb2022-Students#11]
Hola, en el espacio de trabajo del proyecto (descargado directo del github) intenté hacerle catkin_make
Pero me sale el siguiente error:

No he tenido este problema antes, ya intenté ponerlo en un nuevo espacio de trabajo pero esto no lo arregló
¿podrían ayudarme?
Gracias
![Captura de pantalla de 2022-03-07 16-27-49](https://user-images.githubusercontent.com/58478243/157128838-a5ab332d-1ec5-4399-a6bb-d176d8f75e5a.png)

**Comment by MarcFacerias** [comment]
Hola Gerardo, creo que se puede deber a alguna dependencia que no está resuelta, revisa la hoja de requerimientos que te adjunto. Si no es eso, dame el mayor número de detalles que puedas para intentar reproducir este problema en mi lab.
[TEC_FEB2022 Requirements.odt](https://github.com/Manchester-Robotics/ManipulatorsFeb2022-Students/files/8206379/TEC_FEB2022.Requirements.odt)

Un saludo, 
Marc

**Comment by GerardoA01701474** [comment]
Gracias, sí se resolvió :)
