### ISSUE TITLE
Error para mover robot

### ISSUE THREAD

**Issue by MarcosEduardoGarcia** [Manchester-Robotics/ManipulatorsFeb2022-Students#14]
Me marca un error al querer mover el robot

[ INFO] [1646951478.198460631, 1811.904000000]: ABORTED: No motion plan found. No execution attempted

**Comment by MarcFacerias** [comment]
Esto pasa cuando el planner no puede encontrar un path al destino que le estás mandando, revisa que el frame objetivo tenga sentido
