### ISSUE TITLE
Error tf link_base to AnyBox

### ISSUE THREAD

**Issue by Oscar19260** [Manchester-Robotics/ManipulatorsFeb2022-Students#15]
Hola buenas, me aparece este error al querer obtener las posiciones utilizando el comando
``` rosrun tf tf_echo link_base BlueBox ```

Failure at 1657.015000000
Exception thrown:"BlueBox" passed to lookupTransform argument source_frame does not exist. 
The current list of frames is:
Frame world exists with parent sensor_frame.
Frame gazebo_base exists with parent link_base.
Frame link_base exists with parent world.
Frame xarm_gripper_base_link exists with parent link_eef.
Frame link_eef exists with parent link6.
Frame link6 exists with parent link5.
Frame link_tcp exists with parent xarm_gripper_base_link.
Frame left_outer_knuckle exists with parent xarm_gripper_base_link.
Frame link1 exists with parent link_base.
Frame link2 exists with parent link1.
Frame link3 exists with parent link2.
Frame link4 exists with parent link3.
Frame link5 exists with parent link4.
Frame left_finger exists with parent left_outer_knuckle.
Frame left_inner_knuckle exists with parent xarm_gripper_base_link.
Frame right_finger exists with parent right_outer_knuckle.
Frame right_outer_knuckle exists with parent xarm_gripper_base_link.
Frame right_inner_knuckle exists with parent xarm_gripper_base_link.

No se si algun error en el archivo GoalPlanner.py 

pd: yo estoy utilizando la versión ros noetic.

**Comment by MarcFacerias** [comment]
He testeado el mismo ejemplo que has comentado y el frame BlueBox existe y tf lo detecta, pero no puedo asegurar que el mismo código funcione en noetic. Revisa bien que todos los códigos requeridos estén funcionando sin errores, aparte de algún problema con los archivos de ros no se me ocurre que podría estar pasando.

![Screenshot from 2022-03-12 19-18-35](https://user-images.githubusercontent.com/38987718/158032257-ad84cde5-62a0-420e-949f-c0ddb9496114.png)
.
