### ISSUE TITLE
Echo to topics /planning_scene and /planning_scene_world

### ISSUE THREAD

**Issue by carlosahs** [Manchester-Robotics/ManipulatorsFeb2022-Students#16]
Hi, whenever I execute either `rostopic echo /planning_scene` or `rostopic echo /planning_scene_world`, I am prompted with the following warning:

```
WARNING: no messages received and simulated time is active.
Is /clock being published?
```

Do we have to publish /clock? My team is exploring these topics because with are having trouble adding obstacles and we think the problem is that the scene we are using should be one involving those topics. Our code creates a scene:

```python
# >>> Inside solution_template.py
# Instantiate a PlanningSceneInterface object
scene = moveit_commander.PlanningSceneInterface()
""" 
**************************
Adding Objects to the Planning Scene
**************************
""" 
#Cargo names
targets = ["RedBox",
           "BlueBox",
           "GreenBox"]

Rbox_pose = geometry_msgs.msg.PoseStamped()
Bbox_pose = geometry_msgs.msg.PoseStamped()
Gbox_pose = geometry_msgs.msg.PoseStamped()
Rbox_pose.header.frame_id = targets[0]
Bbox_pose.header.frame_id = targets[1]
Gbox_pose.header.frame_id = targets[2]
# RED
Rbox_pose.pose.orientation.w = 1.0
Rbox_pose.pose.position.z = 0
Rbox_name = "RedBox"
# BLUE
Bbox_pose.pose.orientation.w = 2.0
Bbox_pose.pose.position.z = 0
Bbox_name = "BlueBox"
# GREEN
Gbox_pose.pose.orientation.w = 3.0
Gbox_pose.pose.position.z = 0
Gbox_name = "GreenBox"
scene.add_box(Rbox_name, Rbox_pose, size=(0.06, 0.06, 0.06))
scene.add_box(Bbox_name, Bbox_pose, size=(0.06, 0.06, 0.06))
scene.add_box(Gbox_name, Gbox_pose, size=(0.06, 0.06, 0.06))
```

The above code produces the following abortion:
```
[ INFO] [1647044952.090424407, 265.147000000]: ABORTED: No motion plan found. No execution attempted.
```

We also have the doubt about what motion plan the message is referring to.

**Comment by MarcFacerias** [comment]
You shouldn't need to use those topics, I'm quite confused by the error msg but I can see that you are not defining the orientation of the boxes properly (blue and green quaternions are not valid). You can refer to an older issue where we talk about them. Regarding the rest of the code double-check the MoveIt Python API documentation to see what is expected in the field _header.frame_id_ and if some kind of check needs to be done after spawning a box.
