### ISSUE TITLE
roslaunch xarm_gazebo xarm6_challenge.launch not working properly on my computer

### ISSUE THREAD

**Issue by GinfinitFC** [Manchester-Robotics/ManipulatorsFeb2022-Students#19]
Hola buen dia, estaba intentando correr la simulacion del reto en mi computadora, estoy haciendo dual boot y al intentar correr el mundo me sale el siguiente warning:
[spawn_gazebo_model-6] process has finished cleanly
log file: /home/giancarlo/.ros/log/b7875ed4-a25c-11ec-a0d6-e094677fbe80/spawn_gazebo_model-6*.log
[WARN] [1647127997.717457, 3.897000]: Controller Spawner couldn't find the expected controller_manager ROS interface.
[xarm/gripper_controller_spawner-8] process has finished cleanly
En una anterior iteracion descargue una libreria de control para python, libreria que no me funciono por lo que tuve que desinstalarla con pip uninstall control, este warning tampoco me dejo controlar el puzzlebot con el teclado.
Mi sospecha es que al descargar control de python se mezclo de alguna manera con el package de control de ros, ya elimine y reinstale pero aun me sigue apareciendo el warning, y el problema es que desde un inicio el brazo robot me aparece ya colisionado con la mesa y no me deja realizar ningun movimiento desde rviz con moveit.

**Comment by MarcFacerias** [comment]
Yo intentaria reinstalar las dependencias que os pasamos, deberia depender de los paquetes de control. 

- sudo apt-get install ros-melodic-ros-control ros-melodic-ros-controllers
- sudo apt-get install ros-melodic-gazebo-ros-pkgs ros-melodic-gazebo-ros-control

Si todos los paquetes se instalan sin problemas seguire investigando.

**Comment by GinfinitFC** [comment]
Vale muchisimas, ya me funciona, si me estaba haciendo falta el segundo package
