### ISSUE TITLE
Ignorar warnings en Ros

### ISSUE THREAD

**Issue by Oscar19260** [Manchester-Robotics/ManipulatorsFeb2022-Students#20]
Hola buen día, tengo la duda de si hay alguna manera de emitir warnings en ROS, me aparece este ```[ WARN] [1647204779.877302718, 920.010000000]: TF_REPEATED_DATA ignoring data with redundant timestamp``` estuve investigando, pero no encontré ninguna forma.

**Comment by MarcFacerias** [comment]
you can find logging details in http://wiki.ros.org/roscpp/Overview/Logging, if you want to add warnings in your code the syntaxis is ROS_WARN(...).
