### ISSUE TITLE
Duda con función addObstacles

### ISSUE THREAD

**Issue by ParzivalStark** [Manchester-Robotics/ManipulatorsFeb2022-Students#21]
Según entiendo esta función es para añadir las cajas en rviz con el moveit commander, mi duda es si las cajas de deposito tienen que estar huecas como se ven en gazebo o pueden ser cajas normales.

**Comment by MarcFacerias** [comment]
Hola, en mi experiencia move it trata las cajas como regiones del espacio donde hay un obstaculo, nunca me he encontrado con la possibilidad de darle propiedades fisicas a las cajas.

**Comment by ParzivalStark** [comment]
Oh, esta bien, gracias
