### ISSUE TITLE
Add Obstacles

### ISSUE THREAD

**Issue by MarcosEduardoGarcia** [Manchester-Robotics/ManipulatorsFeb2022-Students#22]
Aplico la funcion para spawnear objetos en RVIZ en otros proyectos de prueba y salen los objetos aplico lo mismo en el reto sin embargo no logro que se muestren las cajas en rviz ayuda po favo

**Comment by MarcFacerias** [comment]
Hola Marcos, 

Necesitaria un poco mas de informacion para poder ayudarte, mandame codigo que pueda reproducir en mi laboratorio y miro que podria estar pasando.
