### ISSUE TITLE
Problema con la función attachBox

### ISSUE THREAD

**Issue by Franco-A01733927** [Manchester-Robotics/ManipulatorsFeb2022-Students#23]
Hola, primero que nada espero esten muy bien.

Ahora bien, el problema que tengo es que, aunque el programa corre sin problemas al seguir y planear las trayectorias, surge un problema al intentar tomar y dejar los cubos en las cajas, ya que al intentar trasladarlos nos avienta el siguiente error:

**[ERROR] [1647324655.272066541, 43.398000000]: Attempting to attach object 'GreenBox' to link 'link_tcp' but no geometry specified and such an object does not exist in the collision world**

Pero el programa sigue corriendo y posteriormente sale el segundo error:

**[ERROR] [1647324703.433710824, 50.506000000]: Attached body 'GreenBox' not found**

Esto para cada uno de los cubos y no queremos tocar archivos que nos puedan causar problemas más adelante como los parámetros de los cubos o del mundo, por lo que nos seria de mucha ayuda su consejo de si hay que modificar algún parámetro dentro de los archivos del mundo o por el contrario nos hace falta algo en nuestra función, lo cual vemos más probable, a continuación un screenshot de como están definidas las funciones para agarrar y soltar.

![Screenshot from 2022-03-15 00-26-24](https://user-images.githubusercontent.com/67660198/158319609-5d5c607b-f500-4fef-ae62-61ca93c03487.png)

Espero me puedan ayudar, muchisimas gracias.

**Comment by MarcFacerias** [comment]
Por lo que veo diria que el error proviene de como estan definidas las cajas en moveit. Revisad con la interficie que las cajas aparezcan en rviz y que el nombre "GreenBox" sea el mismo que usasteis al crearlas.
