### ISSUE TITLE
Gazebo detiene el tiempo

### ISSUE THREAD

**Issue by DannyAvilaL** [Manchester-Robotics/ManipulatorsFeb2022-Students#24]
**Tema que surgió en el breakout room:**

En algunas ocasiones cuando realizaba la prueba del funcionamiento del xarm, gazebo detenía el tiempo por completo de la simulación y en la terminal no aparecía ningún mensaje de error. Tengo partición en dual boot. 

De acuerdo con Rebeca, unas de las razones de esto son: configuración de la computadora, tarjeta gráfica, algunos procesos de Gazebo se siguen ejecutando (después de haber cerrado el proceso principal en la terminal).

De acuerdo con Marc, se pueden usar los siguientes comandos:
`$ killall gzserver`
`$ killall gzclient`

Una de mis "soluciones" fue desactivar las sombras del sol, pero Marc mencionó que hay otras configuraciones que se pueden modificar para mejorar el rendimiento, dejo el Issue abierto para que las pueda colocar :)

**Comment by MarcFacerias** [comment]
Te dejo una lista de posibles fix para este problema:

1. Lanzar gazebo sin GUI: <arg name="gui" default="false" doc="Starts gazebo gui" /&gt; Es la última opcion, ya que no verás la simulación, pero puedes seguir el brazo y las cajas en Rviz ploteando las tfs.
2. Desactivar las sombras y todos los elementos visuales que no sean imprescindibles en la simulación. 
3. Cambiar la configuración del motor de físicas (el software que utiliza gazebo para su simulación). Para hacer eso deberías abrir el mundo sin el robot con el comando 'gazebo {path al archivo .world}' y una vez dentro clicar en la opción _Physics_ y jugar con los parámetros _max_step_size_ y lo del solver. Esto cambiará la precisión del simulador, pero debería reducir la carga de tu ordenador y mejorar la performance de gazebo.
