### ISSUE TITLE
Rospy.init()

### ISSUE THREAD

**Issue by JorgePerC** [Manchester-Robotics/ManipulatorsFeb2022-Students#25]
Holaa, buenas noches
Me preguntaba si en solution Template debemos de inicializar un nodo de ros en específico.
Por el momento nosotros hacemos
 > rospy.init_node(“nyNode”, anonymous =True)

Pero como sólo se puede hacer un init node, no sé si eso esté bien, o debamos de llamar a otro nodo más relevante

gracias c:

**Comment by MarcFacerias** [comment]
Este comando convierte tu código en un nodo y le asigna un nombre, el string "myNode" podria ser el que tú quisieras, su única utilidad es identificar el nodo en los mensajes de terminal, por ejemplo en el caso de que haya un error en el código.
