### ISSUE TITLE
Archivo faltante

### ISSUE THREAD

**Issue by JorgePerC** [Manchester-Robotics/ManipulatorsFeb2022-Students#5]
Hola, estaba haciendo la actividad de Gazebo, pero me temo no está el archivo de "spawn_puzzlebot_gazebo.launch"

¿Deberíamos de crearlo nosotros?

**Comment by MarcFacerias** [comment]
Hola Jorge, 

Estoy un poco confundido respecto pregunta, podrías darme un poco de contexto para localizar el error? Me vendría bien saber que workspace estás usando y en que archivo se llama a spawn_puzzlebot_gazebo.launch. Si lo prefieres puedes subir archivos a este issue para que ejecute el código yo mismo.

Un saludo, 
Marc

**Comment by rebecavelasco** [comment]
Hola, Jorge: 

Estoy revisando que ese archivo no estaba disponible con el nombre correcto.  Por favor puedes encontrar ese archivo en el path /24_02_2022/ws/src/puzzlebot_gazebo/launch/spawn_puzzlebot_gazebo.launch

El folder esta ya actualizado.

Una disculpa, cualquier otra cosa, hazmela saber. 

Un saludo, 
Rebeca

**Comment by rebecavelasco** [comment]
Hola, Jorge:

En este caso cambiar el nombre no soluciona el error, porque el archivo no es el correcto. Ya puedes encontrar en la carpeta el archivo correcto. La razon es que los archivos en esa carpeta pertenecen a otro controlador.

Una gran disculpa.

Por favor mentenme al tanto de como resulta.

Saludos,

Rebeca

**Comment by JorgePerC** [comment]
Jajaja, no me odies 😿 
Ahora marca otro, se borró el src de puzzeblot_control
![image](https://user-images.githubusercontent.com/42452493/156420796-e42616de-86be-4942-bebf-13ed4ba8df9b.png)

**Comment by rebecavelasco** [comment]
Es porque los archivos en ese path no los necesitas. Utiliza el archivo que esta en el path, 

Manchester-Robotics/ManipulatorsFeb2022-Students/24_02_2022/ws/src/puzzlebot_control/CMakeLists.txt

que ya no lo incluye, o baja otra vez el folder completo de puzzlebot_control.  

Y no te preocupes, no te odio. De hecho, Gracias por tu feedback, y sorry por las molestias.

**Comment by JorgePerC** [comment]
Uhhh, creo que ya está, me basé en el solution pq me estaba dando otro error, pero al final me dí cuenta que mi transmisión no era de velocidad 😄. 
Al correrlo, dice que no hay un p gain para pid, pero eso creo que ya es otra cosa. Sale lo mismo en el solution
En mi branch me marca otro de spawn, pero haré otro issue para preguntar que pasa 😃 

Muchas gracias, saludos!
