### ISSUE TITLE
¿Dónde debo guardar el archivo con las paredes?

### ISSUE THREAD

**Issue by OSWA00** [Manchester-Robotics/ManipulatorsFeb2022-Students#6]

**Comment by MarcFacerias** [comment]
Hola, este tipo de archivos se suelen guardar en la carpeta worlds de tu package, en este caso seria src/puzzlebot_world/worlds. Puedes guardarlo en cualquier package y encontrarlo a través de los launch files. Te dejo un ejemplo:

`  <include file="$(find gazebo_ros)/launch/empty_world.launch">
    <arg name="world_name" value="$(find puzzlebot_world)/worlds/track.world"/>
    <arg name="debug" value="$(arg debug)" />
    
    <arg name="gui" value="$(arg gui)" />
    <arg name="paused" value="$(arg paused)"/>
    <arg name="use_sim_time" value="$(arg use_sim_time)"/>
    <arg name="headless" value="$(arg headless)"/>
  </include>`

En este caso se utiliza empty_world.launch(escrito por gazebo) para lanzar un mundo que está en src/puzzlebot_world)/worlds/track.world

**Comment by rebecavelasco** [comment]
Hola, el mundo que creaste (room.world) va en el path que dice Marc. El archivo de las paredes al ser un modedo, se guarda en src/puzzlebot_world/models.

Saludos,

Rebeca
