### ISSUE TITLE
tf vs tf2

### ISSUE THREAD

**Issue by Oscar19260** [Manchester-Robotics/ManipulatorsFeb2022-Students#8]
¿Cuál es la diferencia entre el uso de tf2 con el de tf, y por qué utilizamos tf2 para el nuevo reto?

**Comment by MarcFacerias** [comment]
tf2 es la versión actualizada de tf, aunque creo que la tf original sigue siendo mantenida. Básicamente, la implementación de tf2 es más eficiente y hay ciertas diferencias a la hora de llamar las funciones. En mi experiencia se suele utilizar mayoritariamente tf2, pero sigo usando el tf_echo original, desconozco si hay un equivalente en la nueva versión de la librería, pero no debería suponer un problema.
