### ISSUE TITLE
TF2 duda

### ISSUE THREAD

**Issue by MarcosEduardoGarcia** [Manchester-Robotics/ManipulatorsFeb2022-Students#9]
Cual será el uso que se le dará a TF2?  
Osea haremos uso de TF2 en terminal para ver las coordenadas y rotaciones que resulten al ejecutar plan & execute en Move IT y unicamente pasar esos valores al código o en el código de que manera se implementan las funciones de TF2 ?
Los objetos a mover siempre spawnearan en el mismo lugar? 
El gripper tendra que cerrarse?

En la parte de rotaciones de los tutoriales de TF2 muestra esto
      rotation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
que significa la W?

**Comment by MarcFacerias** [comment]
_**Cual será el uso que se le dará a TF2? Osea haremos uso de TF2 en terminal para ver las coordenadas y rotaciones que resulten al ejecutar plan & execute en Move IT y unicamente pasar esos valores al código o en el código de que manera se implementan las funciones de TF2 ?**_
Tf2 se utiliza para obtener las posiciones de los objetos respecto a distintos ejes de coordenadas y deberias utilizarla en tu codigo para evitar tener que escribir esos valores a mano. 

_**Los objetos a mover siempre spawnearan en el mismo lugar?**_ 
Si, pero intenta diseñar tu solucion lo mas general posible. 

**_El gripper tendra que cerrarse?_**
Si, pero ten en cuenta que deberas usar tanto moveit como el servicio para hacer el attach (uno actua sobre la pinza y el otro une ambos objectos en gazebo)

_**En la parte de rotaciones de los tutoriales de TF2 muestra esto
rotation:
x: 0.0
y: 0.0
z: 0.0
w: 1.0
que significa la W?**_
Estos 4 componentes son una forma de representacion de rotaciones en 3D llama quaternion. Es un standard muy utilizado en el mundo de la robotica y te invito a investigarlos o preguntarle a tus profesores sobre ellos. Te dejo un par de videos:
https://www.3blue1brown.com/lessons/quaternions
https://eater.net/quaternions
